USE redoair;

INSERT INTO `airline` (`name`) VALUES ("Cursus In Hendrerit Institute"),("Metus In Lorem Industries"),("Id Erat Etiam Associates"),("Nunc Mauris Company"),("Consequat Nec Mollis Industries"),("Libero Dui Nec Inc."),("Quam Curabitur Incorporated"),("At Fringilla Inc."),("Luctus Felis Associates"),("Ut Mi Foundation");
INSERT INTO `airline` (`name`) VALUES ("Ac Corp."),("Vel Arcu Curabitur Foundation"),("Nec Consulting"),("Mauris PC"),("Maecenas Libero Est Limited"),("Purus Consulting"),("Mauris Foundation"),("Non Sapien Foundation"),("Et Tristique Industries"),("Ultricies Incorporated");
INSERT INTO `airline` (`name`) VALUES ("Suspendisse Tristique Corporation"),("At LLP"),("Donec Tempor Corporation"),("Nunc Laoreet Company"),("Nulla Tincidunt Consulting"),("Egestas LLP"),("Sed Neque Associates"),("Ipsum Sodales Purus Industries"),("Turpis In Associates"),("Lorem Company");
INSERT INTO `airline` (`name`) VALUES ("Elit Erat Company"),("Pede Consulting"),("Nec Metus LLC"),("Viverra Donec Tempus LLP"),("Vel Lectus LLP"),("Mollis Corporation"),("Proin Company"),("Aenean Eget Magna Company"),("Mauris Industries"),("Luctus LLP");
INSERT INTO `airline` (`name`) VALUES ("Mus Aenean Eget LLP"),("Ullamcorper Eu Euismod PC"),("Enim Consequat Purus Corp."),("Sed PC"),("Tincidunt Pede Ac Associates"),("Ante Institute"),("Sodales Nisi Limited"),("Mattis Limited"),("Aliquet LLC"),("Gravida Sit Amet Inc.");
INSERT INTO `airline` (`name`) VALUES ("Magna Nam Ligula Industries"),("Nunc Quisque Inc."),("In Aliquet Corporation"),("Feugiat Non Lobortis Incorporated"),("Aenean PC"),("Parturient Limited"),("Elit Etiam Limited"),("Nisi A Associates"),("Orci Luctus Inc."),("Tellus Imperdiet Non Associates");
INSERT INTO `airline` (`name`) VALUES ("Mauris Incorporated"),("Diam Foundation"),("Mattis Semper Dui Ltd"),("Placerat Consulting"),("Eget PC"),("Est Mauris Eu Foundation"),("Nulla Cras Limited"),("Velit Quisque Incorporated"),("A Feugiat Tellus PC"),("Ac Mattis Velit Associates");
INSERT INTO `airline` (`name`) VALUES ("Sem Nulla Interdum LLC"),("Euismod Enim Etiam Corporation"),("Duis Risus Odio Foundation"),("Nibh Donec PC"),("Orci Ut Semper Company"),("Dolor Nonummy Ac Corp."),("Lorem Ipsum Dolor Inc."),("At Auctor Company"),("In Consequat Consulting"),("Augue Company");
INSERT INTO `airline` (`name`) VALUES ("Nullam Associates"),("In Felis Industries"),("Enim Etiam Imperdiet Inc."),("Augue LLP"),("Per Conubia Foundation"),("Lectus Quis Limited"),("Sem LLC"),("Malesuada Fames Ac Institute"),("Libero Dui Foundation"),("Sociis Natoque Limited");
INSERT INTO `airline` (`name`) VALUES ("Hendrerit Ltd"),("Nibh Sit PC"),("Porttitor Scelerisque Neque Foundation"),("Dui Fusce Diam Industries"),("Nec Eleifend Ltd"),("Tempor Augue PC"),("Quis Pede LLC"),("Ultricies Industries"),("Netus LLC"),("Mauris Institute");
