/*
-- Query: SELECT * FROM redoair.country
LIMIT 0, 1000

-- Date: 2015-10-08 09:00
*/
INSERT INTO `country` (`id`,`name`) VALUES (1,'Denmark');
INSERT INTO `country` (`id`,`name`) VALUES (2,'Iran');
INSERT INTO `country` (`id`,`name`) VALUES (3,'Chad');
INSERT INTO `country` (`id`,`name`) VALUES (4,'United Kingdom');
INSERT INTO `country` (`id`,`name`) VALUES (5,'USA');
INSERT INTO `country` (`id`,`name`) VALUES (6,'Ivory Coast');
INSERT INTO `country` (`id`,`name`) VALUES (7,'UAE');
INSERT INTO `country` (`id`,`name`) VALUES (8,'Nigeria');
INSERT INTO `country` (`id`,`name`) VALUES (9,'Egypt');
INSERT INTO `country` (`id`,`name`) VALUES (10,'Mexico');
INSERT INTO `country` (`id`,`name`) VALUES (11,'Ghana');
INSERT INTO `country` (`id`,`name`) VALUES (12,'Turkey');
INSERT INTO `country` (`id`,`name`) VALUES (13,'Ethiopia');
INSERT INTO `country` (`id`,`name`) VALUES (14,'Australia');
INSERT INTO `country` (`id`,`name`) VALUES (15,'Yemen');
INSERT INTO `country` (`id`,`name`) VALUES (16,'Russia');
INSERT INTO `country` (`id`,`name`) VALUES (17,'Niger');
INSERT INTO `country` (`id`,`name`) VALUES (18,'Morocco');
INSERT INTO `country` (`id`,`name`) VALUES (19,'Guam');
INSERT INTO `country` (`id`,`name`) VALUES (20,'South Africa');
INSERT INTO `country` (`id`,`name`) VALUES (21,'Puerto Rico');
INSERT INTO `country` (`id`,`name`) VALUES (22,'India');
INSERT INTO `country` (`id`,`name`) VALUES (23,'France');
INSERT INTO `country` (`id`,`name`) VALUES (24,'Japan');
INSERT INTO `country` (`id`,`name`) VALUES (25,'Cyprus');
INSERT INTO `country` (`id`,`name`) VALUES (26,'Kazakhstan');
INSERT INTO `country` (`id`,`name`) VALUES (27,'Norway');
INSERT INTO `country` (`id`,`name`) VALUES (28,'Italy');
INSERT INTO `country` (`id`,`name`) VALUES (29,'Algeria');
INSERT INTO `country` (`id`,`name`) VALUES (30,'Spain');
INSERT INTO `country` (`id`,`name`) VALUES (31,'Syria');
INSERT INTO `country` (`id`,`name`) VALUES (32,'Switzerland');
INSERT INTO `country` (`id`,`name`) VALUES (33,'Jordan');
INSERT INTO `country` (`id`,`name`) VALUES (34,'Netherlands');
INSERT INTO `country` (`id`,`name`) VALUES (35,'Andorra');
INSERT INTO `country` (`id`,`name`) VALUES (36,'Anguilla');
INSERT INTO `country` (`id`,`name`) VALUES (37,'Comoros (Comores)');
INSERT INTO `country` (`id`,`name`) VALUES (38,'Madagascar');
INSERT INTO `country` (`id`,`name`) VALUES (39,'Antigua');
INSERT INTO `country` (`id`,`name`) VALUES (40,'Belgium');
INSERT INTO `country` (`id`,`name`) VALUES (41,'Samoa');
INSERT INTO `country` (`id`,`name`) VALUES (42,'Brazil');
INSERT INTO `country` (`id`,`name`) VALUES (43,'Russian Federation');
INSERT INTO `country` (`id`,`name`) VALUES (44,'Tanzania');
INSERT INTO `country` (`id`,`name`) VALUES (45,'Greece');
INSERT INTO `country` (`id`,`name`) VALUES (46,'Colombia');
INSERT INTO `country` (`id`,`name`) VALUES (47,'Aruba');
INSERT INTO `country` (`id`,`name`) VALUES (48,'Turkmenistan');
INSERT INTO `country` (`id`,`name`) VALUES (49,'Paraguay');
INSERT INTO `country` (`id`,`name`) VALUES (50,'Canada');
INSERT INTO `country` (`id`,`name`) VALUES (51,'New Zealand');
INSERT INTO `country` (`id`,`name`) VALUES (52,'Germany');
INSERT INTO `country` (`id`,`name`) VALUES (53,'Iraq');
INSERT INTO `country` (`id`,`name`) VALUES (54,'Pakistan');
INSERT INTO `country` (`id`,`name`) VALUES (55,'Bahrain');
INSERT INTO `country` (`id`,`name`) VALUES (56,'Azerbaijan');
INSERT INTO `country` (`id`,`name`) VALUES (57,'Mali');
INSERT INTO `country` (`id`,`name`) VALUES (58,'Central African Republic');
INSERT INTO `country` (`id`,`name`) VALUES (59,'Brunei');
INSERT INTO `country` (`id`,`name`) VALUES (60,'Thailand');
INSERT INTO `country` (`id`,`name`) VALUES (61,'Gambia');
INSERT INTO `country` (`id`,`name`) VALUES (62,'Venezuela');
INSERT INTO `country` (`id`,`name`) VALUES (63,'Bangladesh');
INSERT INTO `country` (`id`,`name`) VALUES (64,'Switzerland/France');
INSERT INTO `country` (`id`,`name`) VALUES (65,'China');
INSERT INTO `country` (`id`,`name`) VALUES (66,'Mozambique');
INSERT INTO `country` (`id`,`name`) VALUES (67,'Lebanon');
INSERT INTO `country` (`id`,`name`) VALUES (68,'Yugoslavia');
INSERT INTO `country` (`id`,`name`) VALUES (69,'Belize');
INSERT INTO `country` (`id`,`name`) VALUES (70,'Libya');
INSERT INTO `country` (`id`,`name`) VALUES (71,'Angola');
INSERT INTO `country` (`id`,`name`) VALUES (72,'Bermuda');
INSERT INTO `country` (`id`,`name`) VALUES (73,'Malaysia');
INSERT INTO `country` (`id`,`name`) VALUES (74,'Guinea Bissau');
INSERT INTO `country` (`id`,`name`) VALUES (75,'Malawi');
INSERT INTO `country` (`id`,`name`) VALUES (76,'Burkina Faso');
INSERT INTO `country` (`id`,`name`) VALUES (77,'Netherlands Antilles');
INSERT INTO `country` (`id`,`name`) VALUES (78,'French Polynesia');
INSERT INTO `country` (`id`,`name`) VALUES (79,'Bulgaria');
INSERT INTO `country` (`id`,`name`) VALUES (80,'Slovakia');
INSERT INTO `country` (`id`,`name`) VALUES (81,'Congo');
INSERT INTO `country` (`id`,`name`) VALUES (82,'Barbados');
INSERT INTO `country` (`id`,`name`) VALUES (83,'Hungary');
INSERT INTO `country` (`id`,`name`) VALUES (84,'Argentina');
INSERT INTO `country` (`id`,`name`) VALUES (85,'Zimbabwe');
INSERT INTO `country` (`id`,`name`) VALUES (86,'Burundi');
INSERT INTO `country` (`id`,`name`) VALUES (87,'Romania');
INSERT INTO `country` (`id`,`name`) VALUES (88,'Dominican Republic');
INSERT INTO `country` (`id`,`name`) VALUES (89,'French Guayana');
INSERT INTO `country` (`id`,`name`) VALUES (90,'Philippines');
INSERT INTO `country` (`id`,`name`) VALUES (91,'Zambia');
INSERT INTO `country` (`id`,`name`) VALUES (92,'Iceland');
INSERT INTO `country` (`id`,`name`) VALUES (93,'Bahamas');
INSERT INTO `country` (`id`,`name`) VALUES (94,'Bolivia');
INSERT INTO `country` (`id`,`name`) VALUES (95,'Sri Lanka');
INSERT INTO `country` (`id`,`name`) VALUES (96,'Guinea');
INSERT INTO `country` (`id`,`name`) VALUES (97,'Ireland');
INSERT INTO `country` (`id`,`name`) VALUES (98,'Benin');
INSERT INTO `country` (`id`,`name`) VALUES (99,'Senegal');
INSERT INTO `country` (`id`,`name`) VALUES (100,'Indonesia');
INSERT INTO `country` (`id`,`name`) VALUES (101,'Saudi Arabia');
INSERT INTO `country` (`id`,`name`) VALUES (102,'Tunisia');
INSERT INTO `country` (`id`,`name`) VALUES (103,'Djibouti');
INSERT INTO `country` (`id`,`name`) VALUES (104,'Qatar');
INSERT INTO `country` (`id`,`name`) VALUES (105,'Cameroon');
INSERT INTO `country` (`id`,`name`) VALUES (106,'Croatia (Hrvatska)');
INSERT INTO `country` (`id`,`name`) VALUES (107,'Tadschikistan');
INSERT INTO `country` (`id`,`name`) VALUES (108,'Mayotte');
INSERT INTO `country` (`id`,`name`) VALUES (109,'Chile');
INSERT INTO `country` (`id`,`name`) VALUES (110,'Israel');
INSERT INTO `country` (`id`,`name`) VALUES (111,'Finland');
INSERT INTO `country` (`id`,`name`) VALUES (112,'Uganda');
INSERT INTO `country` (`id`,`name`) VALUES (113,'Armenia');
INSERT INTO `country` (`id`,`name`) VALUES (114,'Portugal');
INSERT INTO `country` (`id`,`name`) VALUES (115,'Martinique');
INSERT INTO `country` (`id`,`name`) VALUES (116,'Sierra Leone');
INSERT INTO `country` (`id`,`name`) VALUES (117,'Wallis and Futuna Islands');
INSERT INTO `country` (`id`,`name`) VALUES (118,'Botswana');
INSERT INTO `country` (`id`,`name`) VALUES (119,'Poland');
INSERT INTO `country` (`id`,`name`) VALUES (120,'Guyana');
INSERT INTO `country` (`id`,`name`) VALUES (121,'Gibraltar');
INSERT INTO `country` (`id`,`name`) VALUES (122,'Sweden');
INSERT INTO `country` (`id`,`name`) VALUES (123,'Cayman Islands');
INSERT INTO `country` (`id`,`name`) VALUES (124,'Austria');
INSERT INTO `country` (`id`,`name`) VALUES (125,'Grenada');
INSERT INTO `country` (`id`,`name`) VALUES (126,'Solomon Islands');
INSERT INTO `country` (`id`,`name`) VALUES (127,'Guatemala');
INSERT INTO `country` (`id`,`name`) VALUES (128,'Ecuador');
INSERT INTO `country` (`id`,`name`) VALUES (129,'Viet Nam');
INSERT INTO `country` (`id`,`name`) VALUES (130,'Cuba');
INSERT INTO `country` (`id`,`name`) VALUES (131,'Hong Kong');
INSERT INTO `country` (`id`,`name`) VALUES (132,'Ibiza/Spain');
INSERT INTO `country` (`id`,`name`) VALUES (133,'New Caledonia');
INSERT INTO `country` (`id`,`name`) VALUES (134,'Peru');
INSERT INTO `country` (`id`,`name`) VALUES (135,'Afghanistan');
INSERT INTO `country` (`id`,`name`) VALUES (136,'Taiwan');
INSERT INTO `country` (`id`,`name`) VALUES (137,'Sudan');
INSERT INTO `country` (`id`,`name`) VALUES (138,'Nepal');
INSERT INTO `country` (`id`,`name`) VALUES (139,'Namibia');
INSERT INTO `country` (`id`,`name`) VALUES (140,'Ukraine');
INSERT INTO `country` (`id`,`name`) VALUES (141,'Rwanda');
INSERT INTO `country` (`id`,`name`) VALUES (142,'King Island');
INSERT INTO `country` (`id`,`name`) VALUES (143,'Jamaica');
INSERT INTO `country` (`id`,`name`) VALUES (144,'Congo (Zaire)');
INSERT INTO `country` (`id`,`name`) VALUES (145,'Zaire');
INSERT INTO `country` (`id`,`name`) VALUES (146,'Kuwait');
INSERT INTO `country` (`id`,`name`) VALUES (147,'Papua New Guinea');
INSERT INTO `country` (`id`,`name`) VALUES (148,'Gabon');
INSERT INTO `country` (`id`,`name`) VALUES (149,'Pazifik Loyaute');
INSERT INTO `country` (`id`,`name`) VALUES (150,'Democratic Republic of The Congo');
INSERT INTO `country` (`id`,`name`) VALUES (151,'Slovenia');
INSERT INTO `country` (`id`,`name`) VALUES (152,'Togo');
INSERT INTO `country` (`id`,`name`) VALUES (153,'Svalbard/Norway');
INSERT INTO `country` (`id`,`name`) VALUES (154,'Teneriffa/Spain');
INSERT INTO `country` (`id`,`name`) VALUES (155,'Malta');
INSERT INTO `country` (`id`,`name`) VALUES (156,'Luxembourg');
INSERT INTO `country` (`id`,`name`) VALUES (157,'Seychelles');
INSERT INTO `country` (`id`,`name`) VALUES (158,'Equatorial Guinea');
INSERT INTO `country` (`id`,`name`) VALUES (159,'Maledives');
INSERT INTO `country` (`id`,`name`) VALUES (160,'Kenya');
INSERT INTO `country` (`id`,`name`) VALUES (161,'Nicaragua');
INSERT INTO `country` (`id`,`name`) VALUES (162,'Swaziland');
INSERT INTO `country` (`id`,`name`) VALUES (163,'Lesotho');
INSERT INTO `country` (`id`,`name`) VALUES (164,'Mauritius');
INSERT INTO `country` (`id`,`name`) VALUES (165,'Belarus');
INSERT INTO `country` (`id`,`name`) VALUES (166,'Somalia');
INSERT INTO `country` (`id`,`name`) VALUES (167,'Liberia');
INSERT INTO `country` (`id`,`name`) VALUES (168,'Uruguay');
INSERT INTO `country` (`id`,`name`) VALUES (169,'Bosnia and Herzegovina');
INSERT INTO `country` (`id`,`name`) VALUES (170,'Oman');
INSERT INTO `country` (`id`,`name`) VALUES (171,'Fiji');
